config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :companies
  end
  namespace :admin do
    resources :login_histories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
    end
  end

  get 'admin', to: 'admin/top#index'
  get 'zip_code/search'

  resources :uploads, only: [:create, :destroy]

  namespace :admin do
    get 'top/index'
    get 'top', to: 'top#index'
    resources :users
    resources :groups
    resources :articles
    resources :inquiries
    put 'users/lock/:id', to: 'users#lock'
    delete 'users/lock/:id', to: 'users#lock'
    patch 'users/confirm/:id', to: 'users#confirm_user', as: 'users_confirm'
    post 'users/resend_confirmation', to: 'users#resend_confirmation'
    resources :login_histories, only: :index
  end

  namespace :public do
  end

  namespace :master do
    resources :cities, only: [:show, :index]
  end

  root 'top#index'
  get 'top/index'


  devise_for :users, only: [:session, :password, :confirmation], controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations'
  }
  patch '/admin/users/confirm/:id', to: 'admin/users#confirm_user', as: 'users_confirm'

end

app/models/admin/article.rb
module Admin
  class Article < Article
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :main_image
  has_many :uploads, dependent: :destroy
  acts_as_taggable

end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < BaseController
    def index
      if request.xhr?
        objects = Admin::Article.all
        if params[:is_publish] == 'all'
        elsif params[:is_publish].present?
          objects = objects.where(is_publish: params[:is_publish])
        end

        if params[:category].present?
          objects = objects.tagged_with(params[:category])
        end
        objects = objects.order('updated_at desc').page(params[:page] || 1).per(20)
        pagination = view_context.paginate(objects, remote: true, window: 1)
        content = render_to_string(partial: 'list.html', locals: {objects: objects})
        render json: {pagination: pagination, content: content, page: params[:page] || 1, status: 'OK'}
      end
    end

    def new
      session[:article_session_id] = Time.zone.now.to_i.to_s + SecureRandom.hex()
      @article = Admin::Article.new
      @article.is_publish = false
    end

    def create
      @article = Admin::Article.new(update_params)
      @article.save!
      Upload.where(article_id: session[:article_session_id]).each do |up|
        up.article_id = @article.id
        up.save
      end
      session[:article_session_id] = nil
      redirect_to admin_articles_path
    end

    def edit
      @article = Admin::Article.find params[:id]
      #@article.content = @article.content.gsub('http://20.188.7.160/s3_images/', 'https://xxxx.com/s3_images/')
    end

    def update
      @article = Admin::Article.find params[:id]
      @article.update(update_params)
      redirect_to admin_articles_path
    end

    def destroy
      @article = Admin::Article.find params[:id]
      @article.destroy
      render json: {status: 200}
    end

    def show
      @article = Admin::Article.find params[:id]
      #@article.content = @article.content.gsub('http://20.188.7.160/s3_images/', 'https://xxxx.com/s3_images/')
    end

    private

    def update_params
      params.require(:admin_article).permit(:title, :catch, :content, :main_image, :tag_list, :is_publish)
    end

  end

end

app/views/admin/articles/_form.html.erb
<%= form_for article do |form| %>
  <div class="card">
    <div class="card-header">
      <strong><i class="fas fa-home"></i>　記事</strong>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-8">
          <div class="form-group">
            <label for="facility_status">公開<span class="label_required">必須</span></label>
            <div class="form-group">
              <div class="form-check form-check-inline mr-1">
                <%= form.radio_button :is_publish, false %>
                <label class="form-check-label" for="admin_article_is_publish_false">下書き</label>
              </div>
              <div class="form-check form-check-inline mr-1">
                <%= form.radio_button :is_publish, true %>
                <label class="form-check-label" for="admin_article_is_publish_true">公開</label>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-8">
          <div class="form-group">
            <label>タイトル<span class="label_required">必須</span></label>
            <%= form.text_field :title, class: 'form-control', placeholder: '記事のタイトルを入力します。', data: {parsley_required: true} %>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="form-group">
            <label>記事見出し</label>
            <%= form.text_area :catch, rows: 5, class: 'form-control', placeholder: '120文字くらいで記事の概要を書きましょう。' %>
          </div>
        </div>

        <div class="col-sm-8">
          <div class="form-group">
            <label>記事カテゴリー<span class="label_required">必須</span></label>
            <%= form.select :tag_list, ArticleCategory.all.map { |c| [c.name, c.name] }, {}, class: 'form-control', selected: article.tag_list.first %>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="form-group">
            <label for="image">記事のメイン画像 (W:1200p x H:630px 推奨)</label>
            <div class="input-group">
              <div class="row">
                <div class="col-sm-12">
                  <div class="image-preview">
                    <% if article.main_image.attached? %>
                      <%= image_tag article.main_image.variant(resize: '600x300').processed, class: 'img-fluid' %>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-12">
                  <label class="wrap-file-button mt-2">
                      <span class="btn btn-primary">
                        <i class="fas fa-file"></i>
                        ファイル選択(jpg)
                        <%= form.file_field :main_image, style: 'display:none', accept: 'image/jpeg' %>
                        <input type="file" style="display:none">
                      </span>
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="field col-sm-12" data-controller="summernote">
          <div class="form-group">
            <label>記事本文</label>
            <%= form.text_area :content, data: {editor: 'summernote'}, style: 'display:none' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="regist-buttons-wrapper">
    <div class="card-footer regist-buttons">
      <button type="submit" class="btn btn-primary">
        <i class="far fa-check-circle"></i> <%= article.new_record? ? '登録' : '更新' %>
      </button>
      <%- if site.present? %>
        <a href="<%= admin_articles_path(id: site.id) %>" class="btn btn-default">
          キャンセル
        </a>
      <%- else
            params[:admin].present? %>
        <a href="<%= admin_articles_path(admin: true) %>" class="btn btn-default">
          キャンセル
        </a>
      <%- end %>
    </div>
  </div>

<% end %>

<%= content_for :add_js do -%>
  <script>
    function sendFile(file, toSummernote) {
      console.log('called sendFile().');
      let data = new FormData();
      data.append('upload[image]', file);
      data.append('upload[article_id]', "<%= article.id || session[:article_session_id] %>");
      $.ajax({
        data: data,
        type: 'POST',
        url: '/uploads.json',
        cache: false,
        contentType: false,
        processData: false,
        success: function (data) {
          let img = document.createElement("IMG");
          img.src = data.url;
          img.setAttribute('style', 'width: 100%');
          img.setAttribute('id', data.upload_id);
          toSummernote.summernote("insertNode", img);
        }
      })
    }

    function deleteFile(file_id) {
      $.ajax({
        type: 'DELETE',
        url: `/uploads/${file_id}`,
        cache: false,
        contentType: false,
        processData: false
      })
    }

    $(function () {
      var form = new FormManager();
      form.init();

      $('[data-editor="summernote"]').summernote({
        height: 800,
        lang: 'ja-JP',
        styleTags: ['p', 'h1', 'h2', 'h3', 'blockquote'],
        callbacks: {
          onImageUpload: function (files) {
            console.log('called onImageUpload.');
            for (let i = 0; i < files.length; i++) {
              sendFile(files[i], $(this))
            }
          },
          onMediaDelete: function (target, editor, editiable) {
            let upload_id = target[0].id;
            if (!!upload_id) {
              deleteFile(upload_id)
            }
            target.remove()
          },
          onPaste: function (e) {
            var bufferText = ((e.originalEvent || e).clipboardData || window.clipboardData).getData('Text');
            e.preventDefault();
            document.execCommand('insertText', false, bufferText);
          }
        },
        toolbar: [
          ['style', ['style']],
          ['paragraph'],
          ['style', ['bold', 'italic', 'underline']],
          ['color', ['color']],
          ['para', ['ul', 'ol']],
          ['link'],
          ['picture'],
          ['video']
        ]
      });
    });
  </script>
<% end -%>

app/views/admin/articles/_list.html+mobile.erb
<table class="table table-responsive-sm">
  <thead>
  </thead>
  <tbody>
  <%- objects.each do |object| %>
    <tr>
      <td><%= object.id %>&nbsp;
        <%- if object.is_publish %>
          <span class="badge badge-pill badge-success">公開</span>
        <%- else %>
          <span class="badge badge-pill badge-light">下書き</span>
        <%- end %>
      </td>
    </tr>
    <tr>
      <td><%= object.title %></td>
    </tr>
    <tr>
      <td align="right"><%= object.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
    </tr>
    <tr>
      <td align="right" style="padding-right: 0">
        <a class="btn-primary btn edit-btn" href="<%= edit_admin_article_path(object) %>"><i class="far fa-edit"></i> 編集</a>&nbsp;
        <a class="btn-primary btn preview-btn" href="<%= admin_article_path(object) %>"><i class="far fa-eye"></i> プレビュー</a>&nbsp;
        <button type="button" class="btn-danger btn delete-btn" data-id="<%= object.id %>"><i class="fas fa-trash"></i>
          削除
        </button>
      </td>
    </tr>
  <%- end %>
  </tbody>
</table>

app/views/admin/articles/_list.html.erb
<table class="table table-responsive-sm">
  <thead>
  <tr>
    <th width="100">記事ID</th>
    <th width="40"></th>
    <th>タイトル</th>
    <th width="150">更新日時</th>
    <th width="300"></th>
  </tr>
  </thead>
  <tbody>
  <%- objects.each do |object| %>
    <tr>
      <td><%= object.id %></td>
      <td>
        <%- if object.is_publish %>
          <span class="badge badge-pill badge-success">公開</span>
        <%- else %>
          <span class="badge badge-pill badge-light">下書き</span>
        <%- end %>
      </td>
      <td><%= object.title %></td>
      <td><%= object.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
      <td align="right">
        <a class="btn-primary btn edit-btn" href="<%= edit_admin_article_path(object) %>"><i class="far fa-edit"></i> 編集</a>&nbsp;
        <a class="btn-primary btn preview-btn" href="<%= admin_article_path(object) %>"><i class="far fa-eye"></i> プレビュー</a>&nbsp;
        <button type="button" class="btn-danger btn delete-btn" data-id="<%= object.id %>"><i class="fas fa-trash"></i>
          削除
        </button>
      </td>
    </tr>
  <%- end %>
  </tbody>
</table>

app/views/admin/articles/_search_box.html.erb
<div class="card search-box search-box-container">
  <div class="card-header">
    <strong><i class="fas fa-search"></i>　記事検索</strong>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <label>カテゴリー</label>
          <select class="form-control select" name="category">
            <option value="">カテゴリーを選択</option>
            <% Article.tag_counts_on(:tags).pluck(:name).each do |category| %>
              <option value="<%= category %>"><%= category %></option>
            <%- end %>
          </select>
        </div>
      </div>
      <div class="col-sm-5">
        <div class="form-group">
          <label>公開状態</label>
          <div class="_container-radio">
            <div class="form-inline">
              <input type="radio" value="all" checked="checked" name="is_publish" id="is_publish_all"/>
              <label class="form-check-label" for="is_publish_all">全て</label>
              <input type="radio" value="true" name="is_publish" id="is_publish_true"/>
              <label class="form-check-label" for="is_publish_true">公開</label>
              <input type="radio" value="false" name="is_publish" id="is_publish_false"/>
              <label class="form-check-label" for="is_publish_false">下書き</label>
            </div>
          </div>
        </div>
      </div>
      <hr/>
    </div>
    <div class="col-sm-12 search-box-buttons">
      <button type="submit" class="search-button btn btn-primary btn-lg"><i class="fas fa-search"></i> 検索</button>
    </div>
  </div>
</div>

<%- content_for :add_js do %>
  <script type="text/javascript">
    // 検索用パラメータ設定
    function searchParams() {
      var searchParams = {};
      <%- if @site.present? %>
      searchParams.id = <%= @site.id %>
        <%- elsif params[:admin].present? %>
        searchParams.admin = true;
      <%- end %>
      searchParams.is_publish = $('[name=is_publish]:checked').val();
      ;
      searchParams.category = $('[name=category]').val();
      return searchParams;
    }

    $(function () {
      new FormManager().init('.search-box');
    });
  </script>
<%- end %>

app/views/admin/articles/edit.html.erb
<%- content_for :title do %>
  記事管理
<%- end %>
<% content_for :breadcrumb do %>
  <% if @site.present? %>
    <% items = [
        {url: '/admin', title: 'ホーム'},
        {title: "店舗一覧", url: admin_shops_path},
        {title: "記事一覧 #{@site.name} (#{@company.name})", url: admin_articles_path(id: @site.id)},
        {title: "記事更新"}
    ] %>
  <% else %>
    <%- items = [
        {url: '/admin', title: 'ホーム'},
        {title: "記事一覧", url: admin_articles_path(admin: true)},
        {title: "記事更新"}
    ] %>
  <%- end %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<div class="container base">
  <div>
    <div class="row">
      <div class="col-sm-12 ">
        <h1 class="func-title">記事更新</h1>
        <%= render partial: 'form', locals: {site: @site, article: @article} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/articles/index.html.erb
<%- content_for :title do %>
  記事管理
<%- end %>
<% content_for :breadcrumb do %>
  <%- if @site.present? %>
    <% items = [
        {url: '/admin', title: 'ホーム'},
        {title: "店舗一覧", url: admin_shops_path},
        {title: "記事管理(#{@site.company.name } - #{ @site.name })"}
    ]
    %>
  <%- else %>
    <% items = [
        {url: '/admin', title: 'ホーム'},
        {title: '記事管理'}
    ]
    %>
  <%- end %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>
<%= render partial: 'base/search_script', locals: {page: params[:page] || 1} %>
<div class="container base">
  <div>
    <div class="row">
      <div class="col-sm-12 ">
        <h1 class="func-title">記事管理</h1>
        <%= render partial: 'search_box' %>
        <div class="card">
          <div class="card-header">
            <strong><i class="far fa-newspaper"></i>　記事一覧</strong>
            <div class="right-button-element">
              <a class="btn-primary btn" href="<%= new_admin_article_path %>"><i class="fas fa-plus"></i> 記事追加</a>
            </div>
          </div>
          <div class="card-body">
            <div class="row mt-10">
              <div class="col-sm-12">
                <div id="content-body"></div>
                <div id="pagination" class="clear"></div>
              </div>
            </div>
            <hr/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :add_js do %>
  <script>

    $(document).on('click', '.delete-btn', function () {
      var id = $(this).data('id');
      swal({
        title: "削除の確認",
        text: 'この記事を削除してよろしいですか？',
        buttons: ["キャンセル", "削除"],
        dangerMode: true,
        icon: 'warning'
      }).then(function (willDelete) {
        if (willDelete) {
          $.ajax({
            method: 'delete',
            url: '/admin/articles/' + id
          }).then(
            function (data) {
              searchManager.getList(<%= params[:page] || 1 %>, searchParams());
            },
            function (data) {
              //error
            }
          );
        }
      });

    });


  </script>



<% end %>

app/views/admin/articles/new.html.erb
<%- content_for :title do %>
  記事管理
<%- end %>
<% content_for :breadcrumb do %>
  <% if @site.present? %>
    <% items = [
        {url: '/admin', title: 'ホーム'},
        {title: "店舗一覧", url: admin_shops_path},
        {title: "記事一覧 #{@site.name} (#{@company.name})", url: admin_articles_path(id: @site.id)},
        {title: "記事作成"}
    ] %>
  <% else %>
    <%- items = [
        {url: '/admin', title: 'ホーム'},
        {title: "記事一覧", url: admin_articles_path},
        {title: "記事作成"}
    ] %>
  <%- end %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>
<div class="container base">
  <div>
    <div class="row">
      <div class="col-sm-12 ">
        <h1 class="func-title">記事登録</h1>
        <%= render partial: 'form', locals: {site: @site, article: @article} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/articles/show.html.erb
<%- content_for :title do %>
  プレビュー
<%- end %>
<% content_for :breadcrumb do %>
  <%- items = [
      {url: '/admin', title: 'ホーム'},
      {title: "記事一覧", url: admin_articles_path},
      {title: "記事プレビュー"}
  ] %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<div class="container base">
  <div>
    <div class="row">
      <div class="col-sm-12 ">
        <div class="card">
          <div class="card-body article">
            <div class="row">
              <div class="col-sm-12">
                <h1 class="title"><%= @article.title %></h1>
              </div>
              <% if @article.main_image.present? %>
                <div class="col-sm-12">
                  <div
                    class="main-image"
                    style="background-image: url(<%=rails_representation_path(@article.main_image.variant(combine_options:{resize:"1200x630^",crop:"1200x630+0+0",gravity: :center}).processed)%>)" %>
                  </div>
                </div>
              <%- end %>
              <% if @article.catch.present? %>
                <div class="col-sm-12">
                  <div class="catch">
                    <%= @article.catch %>
                  </div>
                </div>
              <%- end %>
            </div>
            <div class="row">

              <div class="col-sm-12">
                <%= @article.content.html_safe %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="regist-buttons-wrapper">
      <div class="card-footer regist-buttons">
        <a href="<%= admin_articles_path %>" class="btn btn-default">
          キャンセル
        </a>
        <a href="<%= edit_admin_article_path(id: @article.id) %>" class="btn btn-primary">
          <i class="fas fa-pen"></i> 編集
        </a>
      </div>
    </div>
  </div>
</div>
</div>
<%= content_for :add_js do %>
  <script>
    $(function () {
      var form = new FormManager({img_noimage: '<%= asset_path('noimage.jpg') %>'});
      form.init();
    })
  </script>
<%- end %>