config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :companies
  end
  namespace :admin do
    resources :login_histories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
    end
  end

  get 'admin', to: 'admin/top#index'
  get 'zip_code/search'

  resources :uploads, only: [:create, :destroy]

  namespace :admin do
    get 'top/index'
    get 'top', to: 'top#index'
    resources :users
    resources :groups
    resources :articles
    resources :inquiries
    put 'users/lock/:id', to: 'users#lock'
    delete 'users/lock/:id', to: 'users#lock'
    patch 'users/confirm/:id', to: 'users#confirm_user', as: 'users_confirm'
    post 'users/resend_confirmation', to: 'users#resend_confirmation'
    resources :login_histories, only: :index
  end

  namespace :public do
  end

  namespace :master do
    resources :cities, only: [:show, :index]
  end

  root 'top#index'
  get 'top/index'


  devise_for :users, only: [:session, :password, :confirmation], controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations'
  }
  patch '/admin/users/confirm/:id', to: 'admin/users#confirm_user', as: 'users_confirm'

end

app/models/admin/group.rb
module Admin
  class Group < Group
    has_many :groups_users, class_name: 'Admin::GroupsUser'
    has_many :users, through: :groups_users, class_name: 'Admin::User'
    acts_as_paranoid
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :groups_users
  has_many :users, through: :groups_users
  acts_as_paranoid

  def self.search(params = {})
    groups = Group.all
    groups = groups.where('name like ?', "%#{params[:name]}%") if params[:name].present?
    groups
  end

end

app/models/migration/group.rb
module Migration
  class Group < ApplicationRecord
    class << self
      def load_data
        Group.create(name: 'Group1')
        Group.create(name: 'Group2')
        Group.create(name: 'Group3')
        Group.create(name: 'Group4')
        Group.create(name: 'Group5')
      end
    end
  end
end

app/controllers/admin/groups_controller.rb
#  Admin::GroupsController
#  Generated by LifeCodeCMS Scaffold Generator
module Admin
  class GroupsController < Admin::BaseController
    layout 'application'
    before_action :authenticate_user!
    before_action :check_execute_permission
    before_action :permit_params, only: %i[create update]
    before_action :set_referer, only: [:edit, :new]
    before_action :set_default_params, only: [:edit, :new, :update, :destroy]

    def index
      if request.xhr?
        groups = Admin::Group.search(params).page(params[:page]).per(20)
        pagination = view_context.paginate(groups, remote: true, window: 1)
        content = render_to_string(partial: 'list.html', locals: {search_params: merge_search_params, groups: groups})
        render json: {pagination: pagination, content: content, page: params[:page] || 1, status: 'OK'}
      else
        render
      end
    end

    def new
      flash[:alert] = nil
      if request.xhr?
        render template: 'admin/groups/modal_form', locals: {group: @group}, layout: false
      else
        render
      end
    end

    def edit
      if request.xhr?
        render template: 'admin/groups/modal_form', locals: {group: @group}, layout: false
      else
        render
      end
    end

    def create
      @group = Admin::Group.new(@attr)
      @group.save!
      if request.xhr?
        render json: {status: 200}
      else
        redirect_to session[params[:controller]] && session[params[:controller]]['return_path'] || admin_groups_path
      end
    end

    def update
      begin
        params.keys.each do |key|
          if key.index('delete_') == 0
            if params[key] == 'true'
              item = key.gsub('delete_admin_', '').gsub('group_', '')
              @attr[item] = nil
            end
          end
        end

        if @group.update(@attr)
          if request.xhr?
            render json: {status: 200}
          else
            redirect_to session[params[:controller]] && session[params[:controller]]['return_path'] || admin_groups_path
          end
        else
          flash[:alert] = @group.errors.message
          render template: 'group/edit'
        end
      rescue StandardError => e
        rescue_500(e)
      end
    end

    def destroy
      @group.destroy
      render json: {status: 200}
    end

    private

    def permit_params
      @attr = params.require('admin_group').permit(
          :name, :description
      )
      Group.form_attributes.select { |column| column[:type] == :datetime || column[:type] == :timestamp }.each do |date_column|
        time = params['admin_group'][date_column[:name] + '_time'] || '00:00'
        @attr[date_column[:name]] = "#{@attr[date_column[:name]]} #{time}"
        @attr.delete(date_column[:name] + '_time')
      end
    end

    def set_default_params
      if params[:action] == 'new'
        @group = Admin::Group.new
      else
        @group = Admin::Group.where(id: params[:id]).first
        if @group.nil?
          rescue_404
          return
        end
      end
      @city_data = {}
      Admin::Group.prefecture_attributes.each do |column|
        if column[:city_column].present?
          if @group.new_record?
            @group[column[:name]] = column[:default_prefecture_code] || 1
            prefecture = Prefecture.where(code: @group[column[:name]]).first
            if column[:default_city_code].blank?
              city = City.where(prefecture_code: prefecture.code).first
            else
              city = City.where(code: column[:default_city_code]).first
            end
            @group[column[:city_column]] = city.code
            @group[column[:name].gsub('_code', '_name')] = prefecture.name
            @group[column[:city_column].gsub('_code', '_name')] = city.name
          end
          @city_data[column[:city_column]] = City.where(prefecture_code: @group[column[:name]]).map { |c| [c.name, c.code, {'data-name' => c.name}] }
        end
      end
    end
  end
end

app/views/admin/groups/_form.html.erb
<div class="row">
  <% if flash[:alert] %>
    <div class="col-sm-8">
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    </div>
  <% end %>

  <div class="col-sm-8">
    <div class="form-group">
      <label for="user_name">name</label>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="fas fa-info-circle"></i></span>
        </div>


        <%= form.text_field :name, class: 'form-control',
                            data: {
                                parsley_required: true,
                                parsley_required_message: '氏名を入力して下さい。',
                            }
        %>

      </div>
    </div>
  </div>

  <div class="col-sm-8">
    <div class="form-group">
      <label for="user_name">description</label>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="fas fa-info-circle"></i></span>
        </div>


        <%= form.text_field :description, class: 'form-control',
                            data: {
                                parsley_required: true,
                                parsley_required_message: '氏名を入力して下さい。',
                            }
        %>

      </div>
    </div>
  </div>

</div>

<%- content_for :add_js do %>
  <script>
    $(function () {
      new FormManager({img_noimage: "<%= asset_path('noimage.jpg') %>"}).init();
    });
  </script>
<%- end %>

app/views/admin/groups/_list.html.erb
<table class="table table-responsive-sm">
  <thead>
  <tr>
    <th width="120">ID</th>
    <th>グループ名</th>
    <th>説明</th>
    <th width="200">操作</th>
  </tr>
  </thead>
  <% groups.each do |group| -%>
    <tr>
      <td>
        <div>
          <%= group.id %>
        </div>
      </td>
      <td>
        <%= group.name %>
      </td>
      <td><%= group.description %></td>
      <td>
        <a class="btn-primary btn" href="<%= edit_admin_group_path(group) %>"><i class="far fa-edit"></i> 編集</a>&nbsp;
        <a class="btn btn-danger" href=""><i class="fas fa-trash"></i> 削除</a>&nbsp;
      </td>
    </tr>
  <%- end %>
</table>

app/views/admin/groups/_search_box.html.erb
<div class="card search-box">
  <div class="card-header">
    <strong><i class="fas fa-search"></i>　グループ検索</strong>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="name">グループ名</label>
          <input type="text" class="form-control" id="name" name="name">
        </div>
      </div>
      <hr/>
      <div class="col-sm-12 search-box-buttons">
        <button type="button" class="search-button btn btn-primary btn-lg"><i class="fas fa-search"></i> 検索</button>
      </div>
    </div>
  </div>
</div>

<%- content_for :add_js do %>
  <script>
    // 検索用パラメータ設定
    function searchParams() {
      return {
        name: $('[name="name"]').val()
      };
    }
  </script>
<%- end %>

app/views/admin/groups/edit.html.erb
<%= content_for :breadcrumb do %>
  <% items = [
      {url: '/admin', title: 'ホーム'},
      {url: "#{admin_users_path}", title: 'グループ一覧'},
      {title: 'グループ編集'},
  ]
  %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<div class="container-fluid base">
  <div>
    <%= form_for @group, html: {class: 'form'} do |form| %>
      <div class="row">
        <div class="col-sm-12">

          <h1 class="func-title">グループ編集</h1>

          <div class="card">
            <div class="card-header">
              <strong><i class="fas fa-user-plus"></i>　グループ編集</strong>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-12">
                  <%= render partial: 'form', locals: {form: form, group: @group} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="regist-buttons-wrapper">
        <div class="card-footer regist-buttons">
          <button type="submit" class="btn btn-primary">
            <i class="far fa-check-circle"></i> <%= @group.new_record? ? '登録' : '更新' %>
          </button>
          <a href="<%= admin_groups_path %>" class="btn btn-default">
            キャンセル
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>


<% content_for :add_js do %>
  <script></script>
<%- end %>

app/views/admin/groups/index.html.erb
<%= content_for :breadcrumb do %>
  <% items = [
      {url: '/admin', title: 'ホーム'},
      {title: 'グループ一覧'}
  ]
  %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<%= render partial: 'base/search_script', locals: {page: params[:landing_page] || 1} %>

<div class="container-fluid base">
  <div>
    <div class="row">

      <div class="col-sm-12 ">
        <h1 class="func-title">グループ管理</h1>

        <%= render partial: 'admin/groups/search_box' %>

        <div class="card">
          <div class="card-header">
            <strong><i class="fas fa-users"></i>　グループ一覧</strong>
            <div class="right-button-element">
              <a class="btn-primary btn" href="<%= new_admin_group_path %>"><i class="fas fa-users"></i> グループ追加</a>
            </div>
          </div>
          <div class="card-body">
            <div class="row mt-10">
              <div class="col-sm-12">
                <div id="content-body"></div>
                <div id="pagination" class="clear"></div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/groups/new.html.erb
<%= content_for :breadcrumb do %>
  <% items = [
      {url: '/admin', title: 'ホーム'},
      {url: "#{admin_users_path}", title: 'グループ一覧'},
      {title: 'グループ登録'},
  ]
  %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<div class="container-fluid base">
  <div>
    <%= form_for @group, html: {class: 'form'} do |form| %>
      <div class="row">
        <div class="col-sm-12">

          <h1 class="func-title">グループ登録</h1>

          <div class="card">
            <div class="card-header">
              <strong><i class="fas fa-users"></i>　グループ登録</strong>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-12">
                  <%= render partial: 'admin/groups/form', locals: {form: form, group: @group} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="regist-buttons-wrapper">
        <div class="card-footer regist-buttons">
          <button type="submit" class="btn btn-primary">
            <i class="far fa-check-circle"></i> <%= @group.new_record? ? '登録' : '更新' %>
          </button>
          <a href="<%= admin_groups_path %>" class="btn btn-default">
            キャンセル
          </a>
        </div>
      </div>

    <% end %>
  </div>
</div>