config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :companies
  end
  namespace :admin do
    resources :login_histories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
    end
  end

  get 'admin', to: 'admin/top#index'
  get 'zip_code/search'

  resources :uploads, only: [:create, :destroy]

  namespace :admin do
    get 'top/index'
    get 'top', to: 'top#index'
    resources :users
    resources :groups
    resources :articles
    resources :inquiries
    put 'users/lock/:id', to: 'users#lock'
    delete 'users/lock/:id', to: 'users#lock'
    patch 'users/confirm/:id', to: 'users#confirm_user', as: 'users_confirm'
    post 'users/resend_confirmation', to: 'users#resend_confirmation'
    resources :login_histories, only: :index
  end

  namespace :public do
  end

  namespace :master do
    resources :cities, only: [:show, :index]
  end

  root 'top#index'
  get 'top/index'


  devise_for :users, only: [:session, :password, :confirmation], controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations'
  }
  patch '/admin/users/confirm/:id', to: 'admin/users#confirm_user', as: 'users_confirm'

end

app/models/admin/user.rb
module Admin

  class User < User
    has_many :groups_users, class_name: 'Admin::GroupsUser'
    has_many :groups, through: :groups_users, class_name: 'Admin::Group'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :lockable, :rememberable, :recoverable, :confirmable, :trackable
  acts_as_paranoid

  has_many :groups_users
  has_many :groups, through: :groups_users
  has_one_attached :avatar

  def operator_role?
    role == 2
  end

  def administrator_role?
    role == 1
  end

  def normal_role?
    role == 3
  end

  def greater_than_equal_to_normal_role?
    true
  end

  def greater_than_equal_to_operator_role?
    role == 1 || role == 2
  end

  def self.search(params = {})
    users = User.all
    users = users.where('name like ?', "%#{params[:name]}%") if params[:name].present?
    users = users.where('name_kana like ?', "%#{params[:name_kana]}%") if params[:name_kana].present?
    users = users.where('email like ?', "%#{params[:email]}%") if params[:email].present?
    users
  end

  def role_name
    if administrator_role?
      Settings.admin.user.role["1"]
    elsif operator_role?
      Settings.admin.user.role["2"]
    else
      Settings.admin.user.role["3"]
    end
  end

  def lock_expired?
    !permanent_lock && locked_at && locked_at < UNLOCK_IN.ago
  end

  if Rails.env == 'production'
    UNLOCK_IN = 60.minutes # 1時間ロック継続
    MAXIMUN_ATTEMPTS = 10 # 10回連続ミスでロック
  else
    UNLOCK_IN = 30.seconds # 1分ロック継続
    MAXIMUN_ATTEMPTS = 3 # 3回連続ミスでロック
  end

  def password_required?
    !persisted? || !password.blank? || !password_confirmation.blank?
  end

  def lock_access!(opts = {})
    self.locked_at = Time.now.utc
    save(validate: false)
  end

  # Unlock a user by cleaning locked_at and failed_attempts.
  def unlock_access!
    self.locked_at = nil
    self.failed_attempts = 0
    save(validate: false)
  end

  def unlock_access
    self.locked_at = nil
    self.failed_attempts = 0
  end


  # Verifies whether a user is locked or not.
  def access_locked?
    !!locked_at && !lock_expired?
  end

  def attempts_exceeded?
    if self.access_locked?
      self.failed_attempts >= MAXIMUN_ATTEMPTS
    else
      false
    end
  end

  def update_failed_attempts
    self.failed_attempts += 1
    save(validate: false)
    if self.failed_attempts >= MAXIMUN_ATTEMPTS
      self.lock_access!
    end
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    layout 'application'

    before_action :authenticate_user!, except: [:confirm_user]
    before_action :check_execute_permission, except: [:confirm_user]
    before_action :permit_params, only: %i[create update]
    before_action :permit_confirm_params, only: :confirm_user

    def index
      if request.xhr?
        users = Admin::User.search(params).order('name_kana').page(params[:page]).per(20)
        # users = users.landing_page(params[:landing_page] || 1).per(20)
        pagination = view_context.paginate(users, remote: true, window: 1)
        content = render_to_string(partial: 'list.html', locals: {users: users})
        render json: {pagination: pagination, content: content, page: params[:page] || 1, status: 'OK'}
      else
        render
      end
    end

    def new
      flash[:alert] = nil
      @user = Admin::User.new
      @user.groups_users.build
      @group_ids = []
    end

    def edit
      @user = Admin::User.where(id: params[:id]).first
      @user.groups_users.build
      @group_ids = @user.groups.pluck(:id)
      rescue_404 if @user.blank?
      rescue_403 if current_user.normal_role? && @user.id != current_user.id
    end

    def create
      if User.where(email: @attr[:email]).first
        @user = Admin::User.new(@attr)
        @user.groups_users.build
        @group_ids = []
        flash[:alert] = 'このメールアドレスは登録済みです。'
        render template: 'admin/users/new'
        return
      end

      @user = Admin::User.new(@attr)
      @user.confirmation_token = SecureRandom.hex(10)
      @user.password = SecureRandom.hex(10)
      @user.save!
      set_groups
      redirect_to admin_users_path
    end

    def update
      @user = Admin::User.where(id: params[:id]).first

      params.keys.each do |key|
        if key.index('delete_') == 0
          if params[key] == 'true'
            item = key.gsub('delete_admin_', '').gsub('user_', '')
            @attr[item] = nil
          end
        end
      end

      if @user.present?
        if @attr[:password] != @attr[:password_confirmation]
          flash[:alert] = '入力されたパスワードが一致しません'
          render template: 'users/edit'
        else
          #begin
          if @user.update(@attr)
            set_groups
            if current_user.normal_role?
              redirect_to admin_top_path
            else
              redirect_to admin_users_path
            end
          else
            flash[:alert] = user.errors.message
            render template: 'users/edit'
          end
        end
      else
        rescue_404
      end
    end

    def confirm_user
      @user = Admin::User.where(id: params[:id]).first
      if @user.update(@attr)
        @user.confirm
        sign_in(@user)
        LoginHistory.create ({
            account: @user.email,
            user_type: 0,
            user_id: @user.id,
            status: 1,
            name: @user.name,
            ip_address: request.remote_ip
        })
        redirect_to admin_top_index_path
      else
        @user.errors
      end
    end

    def lock
      user = Admin::User.find params[:id]
      if request.put?
        user.permanent_lock = true
        user.lock_access!
      elsif request.delete?
        user.permanent_lock = false
        user.unlock_access!
      end
      content = render_to_string(partial: 'lock', locals: {user: user})
      render json: {content: content, status: 'OK'}
    end

    def resend_confirmation
      user = User.where(id: params[:id]).first
      if user.present?
        user.send_confirmation_instructions
        render json: {status: 'OK'}
      else
        render json: {status: 'ERROR'}
      end
    end

    private

    def set_groups
      return if params[:groups_users].blank?
      groups_users = params[:groups_users]
      group_ids = []
      groups_users.keys.each do |key|
        group_ids << groups_users[key][:group_id]
      end
      @user.groups = Group.where(id: group_ids)
    end

    def permit_params
      @attr = params.require('admin_user').permit(:name, :name_kana, :email, :password, :password_confirmation, :role, :avatar)
      @attr[:email] = @attr[:email].downcase if @attr[:email].present?
      if @attr[:password].blank? || params[:edit_password].nil?
        @attr.delete(:password)
        @attr.delete(:password_confirmation)
      end
    end

    def permit_confirm_params
      @attr = params.require('user').permit(:password, :password_confirmation)
    end

  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  layout 'application_sign_in'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    @user = Admin::User.where(confirmation_token: params[:confirmation_token]).first
    rescue_403 if @user.nil?
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'application_sign_in'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    super
    flash[:alert] = 'パスワードをリセットするためのメールを送信しました。'
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
    user = User.reset_password_by_token(params)
    resource.email = user.email
  end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'application'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'application_sign_in'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    @user = User.where(email: params[:user][:email]).first
    if @user.present?
      if @user.valid_password?(params[:user][:password])

        if @user.lock_expired?
          @user.unlock_access
        end

        if @user.access_locked?
          LoginHistory.create ({
              account: params[:user][:email],
              user_type: 0,
              user_id: @user.id,
              status: -1,
              name: @user.name,
              ip_address: request.remote_ip
          })

          flash[:alert] = t('devise.failure.locked')
          @user = User.new
          @user.email = params[:user][:email]
          set_cache_headers
          render template: 'users/sessions/new'
          return
        end

        bypass_sign_in @user
        LoginHistory.create ({
            account: params[:user][:email],
            user_type: 0,
            user_id: @user.id,
            status: 1,
            name: @user.name,
            ip_address: request.remote_ip
        })

        @user.last_sign_in_at = Time.zone.now
        @user.save

        yield resource if block_given?
        respond_with resource, location: after_sign_in_path_for(@user)
      else
        @user.update_failed_attempts
        LoginHistory.create ({
            account: params[:user][:email],
            user_type: 0,
            user_id: @user.present? ? @user.id : -1,
            status: 0,
            name: @user.present? ? @user.name : '',
            ip_address: request.remote_ip
        })

        flash[:alert] = 'メールアドレスまたはパスワードが違います'
        @user = User.new
        @user.email = params[:user][:email]
        set_cache_headers
        render template: 'users/sessions/new'
      end
    else
      if @user
        @user.update_failed_attempts
        LoginHistory.create ({
            account: params[:user][:email],
            user_type: 0,
            user_id: @user.present? ? @user.id : -1,
            status: 0,
            name: @user.present? ? @user.name : '',
            ip_address: request.remote_ip
        })
      end

      flash[:alert] = 'メールアドレスまたはパスワードが違います'
      @user = User.new
      @user.email = params[:user][:email]
      set_cache_headers
      render template: 'users/sessions/new'
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # キャッシュ設定
  def set_cache_headers
    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  layout 'application'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <% if flash[:alert] %>
    <div class="col-sm-12">
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    </div>
  <% end %>
  <div class="col-12">
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <label for="user_name">氏名<span class="label_required">必須</span></label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user-circle"></i></span>
            </div>
            <%= form.text_field :name, class: 'form-control',
                                data: {
                                    parsley_required: true,
                                    parsley_required_message: '氏名を入力して下さい。',
                                }
            %>
          </div>
        </div>
        <div class="form-group">
          <label for="user_name">氏名かな<span class="label_required">必須</span></label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user-circle"></i></span>
            </div>
            <%= form.text_field :name_kana, class: 'form-control',
                                data: {
                                    parsley_required: true,
                                    parsley_required_message: '氏名かなを入力して下さい。',
                                }
            %>
          </div>
        </div>

        <div class="form-group">
          <label for="user_name">メールアドレス<span class="label_required"><%= user.new_record? ? '必須' : '変更不可' %></span></label>

          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">@</span>
            </div>
            <%= form.email_field :email, class: 'form-control', readonly: !user.new_record?,
                                 data: {
                                     parsley_required: true,
                                     parsley_required_message: 'メールアドレスを入力してください。',
                                 } %>
          </div>
        </div>

        <%- if current_user.greater_than_equal_to_operator_role? -%>
          <div class="form-group">
            <label for="user_role">権限</label>
            <div class="col-md-9 col-form-label">
              <% if current_user.administrator_role? %>
                <% Settings.admin.user.role.keys.each_with_index do |role_key, index| %>
                  <div class="form-check form-check-inline mr-1">
                    <%= form.radio_button :role, Settings.admin.user.role_value[Settings.admin.user.role_value.keys[index]] %>
                    <label class="form-check-label" for="admin_user_role_<%= Settings.admin.user.role_value[Settings.admin.user.role_value.keys[index]] %>"><%= Settings.admin.user.role[role_key] %></label>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="form-group">
            <label for="user_group">所属グループ</label>
            <div class="input-group mb-3 payments ">
              <% Group.all.each_with_index do |group, index| %>
                <div class="form-check form-check-inline mr-1">
                  <input type="checkbox"
                         name="groups_users[<%= index %>][group_id]"
                         id="<%= "groups_users_#{index}_group_id" %>"
                         value="<%= group.id %>"
                         <%= @group_ids.index(group.id) ? 'checked' : '' %> />
                  <label for="<%= "groups_users_#{index}_group_id" %>"><%= group.name %></label>
                </div>
              <%- end %>
            </div>
          </div>
        <%- end -%>
      </div>
      <div class="col-sm-4 container-fileinput">
        <div class="form-group">
          <label for="image">プロフィール画像</label>
          <div class="input-group">
            <div class="row">

              <div class="col-12">
                <%- if user.avatar.attached? -%>
                  <div class="image-preview">
                    <%= image_tag representation_image_path(user.avatar.variant(resize:'800x800').processed), class:'img-fluid' %>
                  </div>
                <%- else -%>
                  <div class="image-preview">
                    <%= image_tag asset_path('nouser.jpg') %>
                  </div>
                <%- end -%>
              </div>
              <div class="col-sm-6">
                <label class="wrap-file-button mt-2">
            <span class="btn btn-primary">
              <i class="fas fa-portrait"></i>
              ファイル選択
              <%= form.file_field :avatar, class: '_image', style: 'display:none', accept: 'image/jpeg,image/png' -%>
            </span>
                </label>
              </div>
              <div class="col-sm-6">
                <%- if user.avatar.attached? -%>
                  <label class="wrap-file-button mt-2" style="width: 100%;text-align: right">
                    <span class="btn btn-danger btn-file-delete"><i class="fas fa-trash"></i>&nbsp;<%= Settings.form.label.destroy %></span>
                  </label>
                <% else %>
                  <label class="wrap-file-button mt-2" style="width: 100%;text-align: right;display: none">
                    <span class="btn btn-danger btn-file-delete"><i class="fas fa-trash"></i>&nbsp;<%= Settings.form.label.destroy %></span>
                  </label>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%- unless user.new_record? %>
    <div class="col-sm-8">
      <hr class="mt-lg-3 mb-lg-3"/>
      <div class="form-check form-check-inline mr-1">
        <input type="checkbox" name="edit_password" id="set-password"/><label for="set-password">パスワードを再設定する</label>
      </div>
      <div class="password-config mt-3" style="display: none">
        <div class="form-group">
          <label for="user_role">パスワード</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
          <span class="input-group-text">
            <i class="fas fa-lock"></i>
          </span>
            </div>
            <%= form.password_field :password, class: 'form-control',
                                    autocomplete: 'off',
                                    data: {
                                        parsley_minlength: Settings.security.password.min_length || 8,
                                        parsley_minlength_message: "パスワードは#{Settings.security.password.min_length}文字以上である必要があります。",
                                        parsley_pattern: Settings.security.password.regex,
                                        parsley_pattern_message: Settings.security.password.validate_message || 'パスワードが正しくありません'
                                    }
            %>
          </div>
        </div>
        <div class="form-group">
          <label for="user_role">パスワード(再入力）</label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
          <span class="input-group-text">
            <i class="fas fa-lock"></i>
          </span>
            </div>
            <%= form.password_field :password_confirmation, class: 'form-control',
                                    autocomplete: 'off',
                                    data: {
                                        parsley_equalto: '#admin_user_password',
                                        parsley_equalto_message: 'パスワードが一致していません'
                                    }
            %>
          </div>
        </div>
      </div>
    </div>
  <%- else %>
    <div class="col-sm-8">
      <div class="alert alert-info">
        ユーザー登録すると、登録の手順がメールでユーザーに通知されます。
      </div>
    </div>
  <%- end %>

</div>


<%- content_for :add_js do %>
  <script>
    $(function () {
      var form = new FormManager({img_noimage: '<%= asset_path('noimage.jpg') %>'});
      form.init();
      $("#set-password").on('ifChanged', function () {
        if ($(this).prop("checked")) {
          $(".password-config").fadeIn();
        } else {
          $(".password-config").fadeOut();
        }
      });

      <% if params[:edit_password] %>
      $("#set-password").iCheck("check").iCheck("update");
      <% end %>
    });
  </script>
<%- end %>

app/views/admin/users/_list.html.erb
<table class="table table-responsive-sm">
  <thead>
  <tr>
    <th width="120">ID</th>
    <th>氏名</th>
    <th>権限</th>
    <th>最終ログイン</th>
    <th width="200">操作</th>
  </tr>
  </thead>
  <% users.each do |user| -%>
    <tr>
      <td>
        <div>
          <%= user.id %>
          <% if user.access_locked? %>&nbsp;<span class="danger"> <i class="fas fa-user-lock"></i></span>
          <%- end %>
        </div>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td><%= user_role_icon(user) %> <%= user.role_name %></td>
      <td>
        <%- if user.confirmed_at.nil? && !user.access_locked? %>
          <div>
            <i class="fas fa-user-clock" style="color:#ccc"></i>&nbsp;&nbsp;確認待ち
            <button data-user-id="<%= user.id %>" class="btn-resend btn btn-primary btn-sm">&nbsp;<i class="fas fa-envelope"></i>
              再送
            </button>
          </div>
        <%- else %>
          <%= user.last_sign_in_at ? feed_time(user.last_sign_in_at, true) : '--' %>
        <%- end %>
      </td>
      <td>
        <a class="btn-primary btn" href="<%= edit_admin_user_path(user) %>"><i class="far fa-edit"></i> 編集</a>&nbsp;
      </td>
    </tr>
  <%- end %>
</table>

<script>
  $(function () {

    $(".btn-resend ").on('click', function () {
      var id = $(this).data('user-id');
      $.ajax({
        url: '/admin/users/resend_confirmation',
        data: {id: id, authenticity_token: '<%= form_authenticity_token %>'},
        method: 'post'
      }).done(function (data) {
        if (data.status == 'OK') {
          swal("送信完了", "確認メールを再送しました", "success");
        } else {
          swal("送信失敗", "確認メールの再送ができませんでした。", "error");
        }
      });
    });
  });
</script>

app/views/admin/users/_lock.html.erb
<%- if user.access_locked? -%>
  このユーザーはロックされてます（利用不可）。
  <div class="mt-3">
    <button type="button" class="btn-primary btn lock-btn" data-status="locked"><i class="fas fa-unlock"></i> ロック解除
    </button>
  </div>
<%- else %>
  このユーザーをロック（利用不可に）します。
  <div class="mt-3">
    <button type="button" class="btn-danger btn lock-btn" data-status="unlock"><i class="fas fa-user-lock"></i> ロックする
    </button>
  </div>
<%- end %>

app/views/admin/users/_search_box.html.erb
<div class="card search-box">
  <div class="card-header">
    <strong><i class="fas fa-search"></i>　ユーザー検索</strong>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="name">氏名</label>
          <input type="text" class="form-control" id="name" name="name">
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="name_kana">氏名かな</label>
          <input type="name_kana" class="form-control" id="email" name="name_kana">
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label for="email">メールアドレス</label>
          <input type="email" class="form-control" id="email" name="email">
        </div>
      </div>
      <hr/>
      <div class="col-sm-12 search-box-buttons">
        <button type="button" class="search-button btn btn-primary btn-lg"><i class="fas fa-search"></i> 検索</button>
      </div>
    </div>
  </div>
</div>

<%- content_for :add_js do %>
  <script>
    // 検索用パラメータ設定
    function searchParams() {
      return {
        name: $('[name="name"]').val(),
        email: $('[name="email"]').val(),
        name_kana: $('[name="name_kana"]').val()
      };
    }
  </script>
<%- end %>

app/views/admin/users/edit.html.erb
<%= content_for :breadcrumb do %>
  <%- if current_user.normal_role? %>
    <% items = [
        {url: '/admin', title: 'ホーム'},
        {title: 'ユーザー編集'},
    ]
    %>
  <%- else %>
    <% items = [
        {url: '/admin', title: 'ホーム'},
        {url: "#{admin_users_path}", title: 'ユーザー一覧'},
        {title: 'ユーザー編集'},
    ]
    %>
  <%- end %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<div class="container-fluid base">
  <div>
    <%= form_for @user, html: {class: 'form'} do |form| %>
      <div class="row">
        <div class="col-sm-12">

          <h1 class="func-title">ユーザー編集</h1>

          <div class="card">
            <div class="card-header">
              <strong><i class="fas fa-user-plus"></i>　ユーザー編集</strong>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-12">
                  <%= render partial: 'form', locals: {form: form, user: @user} %>
                </div>
                <%- if current_user && current_user.greater_than_equal_to_operator_role? && @user.id != current_user.id%>
                  <div class="col-sm-8">
                    <div class="alert alert-danger mt-3" id="lock-control">
                      <%= render partial: 'admin/users/lock', locals: {user: @user} %>
                    </div>
                  </div>
                <%- end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="regist-buttons-wrapper">
        <div class="card-footer regist-buttons">
          <button type="submit" class="btn btn-primary btn-lg">
            <i class="far fa-check-circle"></i> <%= @user.new_record? ? '登録' : '更新' %>
          </button>
          <a href="<%= current_user.normal_role? ? admin_top_path : admin_users_path %>" class="btn  btn-lg btn-default">
            キャンセル
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>


<% content_for :add_js do %>
  <script>
    $(document).on('click', '.lock-btn', function () {
      var status = $(this).data("status");
      var method = 'put';
      if (status == 'locked') {
        method = 'delete';
      }
      $.ajax({
        method: method,
        url: '/admin/users/lock/' + '<%= @user.id %>'
      }).done(function (data) {
        $("#lock-control").html(data.content);
      })
    });
  </script>
<%- end %>

app/views/admin/users/index.html.erb
<%= content_for :breadcrumb do %>
  <% items = [
      {url: '/admin', title: 'ホーム'},
      {title: 'ユーザー一覧'}
  ]
  %>
  <%= render partial: 'layouts/breadcrumb', locals: {items: items} %>
<% end %>

<%= render partial: 'base/search_script', locals: {page: params[:landing_page] || 1} %>

<div class="container-fluid base">
  <div>
    <div class="row">

      <div class="col-sm-12 ">
        <h1 class="func-title">ユーザー管理</h1>

        <%= render partial: 'admin/users/search_box' %>

        <div class="card">
          <div class="card-header">
            <strong><i class="fas fa-user"></i>　ユーザー一覧</strong>
            <div class="right-button-element">
              <a class="btn-primary btn" href="<%= new_admin_user_path %>"><i class="fas fa-user-plus"></i> ユーザー追加</a>
            </div>
          </div>
          <div class="card-body">
            <div class="row mt-10">
              <div class="col-sm-12">
                <div id="content-body"></div>
                <div id="pagination" class="clear"></div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>