config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :companies
  end
  namespace :admin do
    resources :login_histories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
    end
  end

  get 'admin', to: 'admin/top#index'
  get 'zip_code/search'

  resources :uploads, only: [:create, :destroy]

  namespace :admin do
    get 'top/index'
    get 'top', to: 'top#index'
    resources :users
    resources :groups
    resources :articles
    resources :inquiries
    put 'users/lock/:id', to: 'users#lock'
    delete 'users/lock/:id', to: 'users#lock'
    patch 'users/confirm/:id', to: 'users#confirm_user', as: 'users_confirm'
    post 'users/resend_confirmation', to: 'users#resend_confirmation'
    resources :login_histories, only: :index
  end

  namespace :public do
  end

  namespace :master do
    resources :cities, only: [:show, :index]
  end

  root 'top#index'
  get 'top/index'


  devise_for :users, only: [:session, :password, :confirmation], controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      confirmations: 'users/confirmations'
  }
  patch '/admin/users/confirm/:id', to: 'admin/users#confirm_user', as: 'users_confirm'

end

app/views/layouts/_breadcrumb.html.erb
<ol class="breadcrumb">
  <% i = 1 %>
  <% items.each do |item| %>
    <li class="breadcrumb-item" class="<%= item == items.last ? 'active' : '' %>">
      <% unless item[:url].blank? %>
        <a href="<%= item[:url].blank? ? '' : item[:url].force_encoding('UTF-8') %>" itemprop="item">
          <span itemprop="name"><%= sanitize_content item[:title].force_encoding('UTF-8') %></span>
        </a>
      <% else %>
        <span itemprop="name"><%= sanitize_content item[:title].force_encoding('UTF-8') %></span>
      <% end %>
    </li>
    <% i += 1 %>
  <% end %>
</ol>

app/views/layouts/_footer.html.erb
<footer class="app-footer">
  <div>
    <%= Settings.common.app_name %>
    <span><%= raw Settings.common.copyright %></span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    <img class="navbar-brand-full" src="<%= asset_path('brand/logo.png') %>" width="160" alt="CoreUI Logo">
    <img class="navbar-brand-minimized" src="<%= asset_path('brand/logo.png') %>" width="30" height="30" alt="CoreUI Logo">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="nav navbar-nav d-md-down-none">

  </ul>

  <ul class="nav navbar-nav ml-auto">
    <% if current_user.present? %>
      <li class="nav-item px-3 welcome-name">
        <div class="avatar">
          <%- if current_user.avatar.attached? %>
            <%= image_tag(url_for(current_user.avatar.variant(gravity: :center, resize: "120x120^", crop: "120x120+0+0").processed)) %>
          <%- else %>
            <%= image_tag(asset_path('nouser-circle.jpg')) %>
          <%- end %>
        </div>
      </li>
      <li class="nav-item px-3 welcome-name">
        ようこそ <b><%= current_user.name %></b> さん
      </li>
      <li class="nav-item px-3">
        <a href="<%= destroy_user_session_path %>" class="nav-link" data-method="delete"><i class="fas fa-sign-out-alt"></i>
          ログアウト</a>
      </li>
    <%- else %>
      <li class="nav-item px-3">
        <a href="<%= new_user_session_path %>" class="nav-link"><i class="fas fa-sign-in-alt"></i> サインイン</a>
      </li>
    <%- end %>
  </ul>
</header>

app/views/layouts/_side_bar.html.erb
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <%- if current_user && current_user.greater_than_equal_to_operator_role? %>
        <li class="nav-title">管理</li>

        <li class="nav-item nav-dropdown">
          <a class="nav-link nav-dropdown-toggle" href="#">
            <i class="fas fa-users-cog"></i> <span>ユーザー管理</span>
          </a>
          <ul class="nav-dropdown-items">
            <li class="nav-item" data-menu="group">
              <a class="nav-link" href="<%= admin_groups_path %>">
                <i class="fas fa-users"></i> <span>グループ</span>
              </a>
            </li>
            <li class="nav-item" data-menu="user">
              <a class="nav-link" href="<%= admin_users_path %>">
                <i class="fas fa-user"></i> <span>ユーザー</span>
              </a>
            </li>
          </ul>
        </li>
      <%- end %>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE>
<html html lang="ja">
<head>
  <title><%= Settings.common.app_name %></title>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>

<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">

<%= render partial: 'layouts/header' %>

<div class="app-body">

  <%#= yield %>
  <%= render partial: 'layouts/side_bar' %>
  <main class="main">
    <!-- Breadcrumb-->
    <%= yield(:breadcrumb) if content_for?(:breadcrumb) %>

    <div class="container">
      <%= yield %>
    </div>
  </main>


</div>

<%= render partial: 'layouts/footer' %>
<div
  id="image-path"
  data-noimage-image-path="<%= asset_path('noimage.jpg') %>"
  data-nodocument-image-path="<%= asset_path('nodocument.jpg') %>"
  data-document-image-path="<%= asset_path('document.jpg') %>"
  style="display: none">
</div>
</body>
<%= javascript_include_tag 'application' %>
<%= content_for :add_js if content_for?(:add_js) %>
<script>
  $(function () {
    $(".nav-item .nav-link").removeClass("active");
    <%- if params[:controller] == 'published_histories' && params[:action] == 'new' %>
    $(".nav-item[data-menu='facility'] .nav-link").addClass("active");
    <%-else %>
    $(".nav-item[data-menu=<%=params[:controller].gsub('master/','').gsub('admin/','').singularize%>] .nav-link").addClass("active");
    <%- end %>
  });
</script>
</html>

app/views/layouts/application_public.html.erb
<!DOCTYPE>
<html html lang="ja">
<head>
  <title><%= Settings.common.app_name %></title>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>

<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">

<%= render partial: 'layouts/header' %>

<div class="app-body">

  <%#= yield %>
  <%= render partial: 'layouts/side_bar' %>
  <main class="main">
    <!-- Breadcrumb-->
    <%= yield(:breadcrumb) if content_for?(:breadcrumb) %>

    <div class="container">
      <%= yield %>
    </div>
  </main>


</div>

<%= render partial: 'layouts/footer' %>

</body>
<%= javascript_include_tag 'application' %>
<%= content_for :add_js if content_for?(:add_js) %>
<script>
  $(function () {
    $(".nav-item .nav-link").removeClass("active");
    <%- if params[:controller] == 'published_histories' && params[:action] == 'new' %>
    $(".nav-item[data-menu='facility'] .nav-link").addClass("active");
    <%-else %>
    $(".nav-item[data-menu=<%=params[:controller].gsub('master/','').gsub('admin/','').singularize%>] .nav-link").addClass("active");
    <%- end %>
  });
</script>
</html>

app/views/layouts/application_sign_in.html.erb
<!DOCTYPE>
<html html lang="ja">
<head>
  <title><%= Settings.common.app_name %></title>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <meta name="robots" content="noindex"/>
</head>

<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">

<div class="app-body">
  <main class="main_public">
    <div class="container public">
      <%= yield %>
    </div>
  </main>
</div>

<footer class="app-footer" style="margin-left:0">
  <div>
    <%= Settings.common.app_name %>
    <span>&copy; 2019-2020 <%= Settings.common.copyright %>.</span>
  </div>
</footer>

</body>
<%= javascript_include_tag 'application' %>
<%= content_for :add_js if content_for?(:add_js) %>
</html>